### ISSUE TITLE
Setup KanBan for fullStack group_capstone

### ISSUE THREAD

**Issue by emmanuelsteven** [emmanuelsteven/heli-hire-captone-backend#12]
collaborators in this project include;
- @Reggeditt 
- @emmanuelsteven 
- @bronnie313 
- @IsmailChangezi 
 this is the [link to our project 
](https://github.com/users/emmanuelsteven/projects/13/views/1)
<img width="1680" alt="Screenshot 2023-09-28 at 12 21 58" src="https://github.com/emmanuelsteven/Final-group-capstone-BackEnd/assets/114663161/cf63fd0a-ab91-4008-a273-f5acde2c6bcc">

**Comment by Meltrust** [comment]
Hi @emmanuelsteven

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a link fo the Kanban board that is private.  I cannot access it for review:

![image](https://github.com/emmanuelsteven/Final-group-capstone-BackEnd/assets/57421823/c8eac99e-1c85-468e-9bcb-ddc080b3431a)

Kindly make the project public.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @emmanuelsteven ,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete

### To highlight

- All cards have descriptions, are fairly pointed, and have assignees✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
